version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgresDb:/var/lib/postgresql/data
volumes:
  postgresDb:
