### Health Check
GET http://localhost:8080/api/healthcheck

# ### List
# GET http://localhost:8080/api/getUsers

### Login User
POST http://localhost:8080/api/login
content-type: application/json

{
    "username": "username",
    "password": "password"
}

### Create User
POST http://localhost:8080/api/register
content-type: application/json

{
    "username": "username",
    "password": "password",
    "email": "johndoe@gmail.com",
    "phone": "0123456789",
    "role": "User",
    "name": "John Doe"
}

# ### Update
# PATCH http://localhost:8080/api/notes/59853082-fcaf-456c-8969-9321ea08cddd
# content-type: application/json

# {
#     "content": "here some reminder, mention @raditzlawliet share and like"
# }

# ### Delete
# DELETE http://localhost:8080/api/notes/bcc09bc9-710f-45b4-829c-b3523ee87998